# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      pipenv install
    command: echo 'start script'

vscode:
  extensions:
    - ms-python.python
